version: '3.4'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_qa
      MONGO_INITDB_ROOT_PASSWORD: S@igon@2020QA
    volumes:
      - ./data:/data/db
#Docker Networks
networks:
  default:
    external:
      name: localhost
