version: "3.6"

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt-site:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/etc/qa/ssl
    container_name: 3km_server
    hostname: 3km_server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
networks:
  default:
    external:
      name: localhost
