version: '3.4'

services:
  redis:
    image: redis
    container_name: 3km_redis
    volumes:
      - $PWD/redisdata:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

#Docker Networks
networks:
  default:
    external:
      name: localhost
